CC = gcc

SRC_DIR = src
LIB_DIR = $(SRC_DIR)/libs
BUILD_DIR = build

AWS_IOT_SDK_C_LIB_DIR += $(LIB_DIR)/aws-iot-device-sdk-embedded-C
AWS_IOT_SDK_PLATFORM_DIR += $(AWS_IOT_SDK_C_LIB_DIR)/platform/linux/mbedtls
AWS_IOT_SDK_PLATFORM_COMMON_DIR += $(AWS_IOT_SDK_C_LIB_DIR)/platform/linux/common
AWS_IOT_SDK_INCLUDE_DIRS += -I $(AWS_IOT_SDK_C_LIB_DIR)/include
AWS_IOT_SDK_INCLUDE_DIRS += -I $(AWS_IOT_SDK_C_LIB_DIR)/external_libs/jsmn
AWS_IOT_SDK_INCLUDE_DIRS += -I $(AWS_IOT_SDK_PLATFORM_COMMON_DIR)
AWS_IOT_SDK_INCLUDE_DIRS += -I $(AWS_IOT_SDK_PLATFORM_DIR)
AWS_IOT_SDK_C_MBEDTLS_LIB += $(AWS_IOT_SDK_C_LIB_DIR)/external_libs/mbedTLS

AWS_IOT_SRC_FILES += $(shell find $(AWS_IOT_SDK_C_LIB_DIR)/src -name '*.c')
AWS_IOT_SRC_FILES += $(shell find $(AWS_IOT_SDK_C_LIB_DIR)/external_libs/jsmn -name '*.c')
AWS_IOT_SRC_FILES += $(shell find $(AWS_IOT_SDK_PLATFORM_DIR)/ -name '*.c')
AWS_IOT_SRC_FILES += $(shell find $(AWS_IOT_SDK_PLATFORM_COMMON_DIR)/ -name '*.c')

LOG_FLAGS += -DENABLE_IOT_INFO
LOG_FLAGS += -DENABLE_IOT_WARN
LOG_FLAGS += -DENABLE_IOT_ERROR

COMPILER_FLAGS += -g
COMPILER_FLAGS += $(LOG_FLAGS)

TLS_LIB_DIR += $(AWS_IOT_SDK_C_MBEDTLS_LIB)/library
TLS_INCLUDE_DIR += -I $(AWS_IOT_SDK_C_MBEDTLS_LIB)/include/mbedtls
CERT_DEP_LIBRARY += -L$(TLS_LIB_DIR) -lmbedtls -lmbedx509 -lmbedcrypto -lcjson
EXTERNAL_LIBS += -L$(TLS_LIB_DIR)
LD_FLAG += -Wl,-rpath,$(TLS_LIB_DIR)
LD_FLAG += -ldl $(LIB_DIR)/libmbedtls.a $(LIB_DIR)/libmbedcrypto.a $(LIB_DIR)/libmbedx509.a -lcjson -pthread
AWS_IOT_INCLUDE_ALL_DIRS += $(AWS_IOT_SDK_INCLUDE_DIRS)
AWS_IOT_INCLUDE_ALL_DIRS += $(TLS_INCLUDE_DIR)
AWS_IOT_INCLUDE_ALL_DIRS += $(AWS_APP_INCLUDE_DIRS)

CJSON_LIB_DIR += $(LIB_DIR)/cjson
INCLUDE_CJSON_LIB_DIR += -I $(CJSON_LIB_DIR)

SOCKET_SERVER_COMMAND = socket_server
SOCKET_SERVER_SRC_FILES += $(SRC_DIR)/socket_server.c
SOCKET_SERVER_MAKE_COMMAND = $(CC)  -std=gnu99 $(SOCKET_SERVER_SRC_FILES) -o $(BUILD_DIR)/$(SOCKET_SERVER_COMMAND)

IOT_CLIENT_COMMAND = Iot_$(CLIENT_SUFFIX)
IOT_CLIENT_SRC_FILES += $(SRC_DIR)/iot_client.c
IOT_CLIENT_MAKE_COMMAND = $(CC) $(IOT_CLIENT_SRC_FILES) -o $(BUILD_DIR)/$(IOT_CLIENT_COMMAND)
IOT_CLIENT_MAKE_COMMAND = $(CC)  -std=gnu99 $(IOT_CLIENT_SRC_FILES) $(AWS_IOT_SRC_FILES) -o $(BUILD_DIR)/$(IOT_CLIENT_COMMAND) $(LD_FLAG) $(COMPILER_FLAGS) $(EXTERNAL_LIBS) $(INCLUDE_ALL_DIRS) $(AWS_IOT_INCLUDE_ALL_DIRS) $(INCLUDE_CJSON_LIB_DIR)

all: $(SOCKET_SERVER_COMMAND)

clean:
	rm ./$(BUILD_DIR)/*_$(API_SUFFIX)

$(SOCKET_SERVER_COMMAND):
	$(SOCKET_SERVER_MAKE_COMMAND)